import type { SurfBreak } from "@/lib/types";

/**
 * Curated break catalogue.
 *
 * Coordinates and place names describe real coastlines. `orientationDeg`,
 * `reefSlope` and `depthAtBreakM` are this project's own editorial estimates
 * used by the engine, and the app labels them as such rather than passing them
 * off as survey data. A break only gets a `tideStationId` when NOAA CO-OPS
 * actually publishes predictions for a station in range — where it does not,
 * the tide factor is dropped instead of invented.
 */
export const BREAKS: SurfBreak[] = [
  {
    id: "pago-pago",
    name: "Pago Pago",
    region: "Tutuila",
    country: "American Samoa",
    lat: -14.28,
    lon: -170.69,
    timezone: "Pacific/Pago_Pago",
    breakType: "reef_pass",
    orientationDeg: 155,
    reefSlope: 0.11,
    depthAtBreakM: 1.1,
    tideStationId: "1770000",
    tideStationName: "Pago Pago, American Samoa",
    tideStationDistanceKm: 0,
    blurb:
      "The harbour mouth stands up out of the barrier reef and peels hard left on a big south pulse. It is the reason this app exists: the numbers that make it work arrive days before anyone can see them.",
  },
  {
    id: "piti-bomb-holes",
    name: "Piti Bomb Holes",
    region: "Apra Harbour",
    country: "Guam",
    lat: 13.465,
    lon: 144.652,
    timezone: "Pacific/Guam",
    breakType: "reef_pass",
    orientationDeg: 148,
    reefSlope: 0.13,
    depthAtBreakM: 1.4,
    tideStationId: "1630000",
    tideStationName: "Apra Harbor, Guam",
    tideStationDistanceKm: 0,
    blurb:
      "Three passes cut through the reef flat. The middle one has the steepest face on the island and goes completely hollow when the tide is over the shelf.",
  },
  {
    id: "talofofo-bay",
    name: "Talofofo Bay",
    region: "Santa Rita",
    country: "Guam",
    lat: 13.405,
    lon: 144.783,
    timezone: "Pacific/Guam",
    breakType: "reef",
    orientationDeg: 132,
    reefSlope: 0.08,
    depthAtBreakM: 0.85,
    tideStationId: "1631428",
    tideStationName: "Pago Bay, Guam",
    tideStationDistanceKm: 8,
    blurb:
      "A shallow fringing reef that only stands up on a mid tide. This is the one where getting the tide wrong means getting skinned.",
  },
  {
    id: "sandy-beach",
    name: "Sandy Beach",
    region: "Oʻahu",
    country: "United States",
    lat: 21.268,
    lon: -157.688,
    timezone: "Pacific/Honolulu",
    breakType: "beachbreak",
    orientationDeg: 128,
    reefSlope: 0.05,
    depthAtBreakM: 1.2,
    tideStationId: "1611400",
    tideStationName: "Honolulu, Oʻahu",
    tideStationDistanceKm: 9,
    blurb: "Sharp reef make-up with a close-out on a low tide and a workable shoulder on a mid.",
  },
  {
    id: "waikiki",
    name: "Waikiki",
    region: "Oʻahu",
    country: "United States",
    lat: 21.276,
    lon: -157.827,
    timezone: "Pacific/Honolulu",
    breakType: "reef",
    orientationDeg: 112,
    reefSlope: 0.06,
    depthAtBreakM: 0.95,
    tideStationId: "1611400",
    tideStationName: "Honolulu, Oʻahu",
    tideStationDistanceKm: 9,
    blurb: "Long, slow, shallow. Peel speed is the whole game here, and peel speed is depth, and depth is tide.",
  },
  {
    id: "midway-north-shore",
    name: "North Shore",
    region: "Midway Atoll",
    country: "United States",
    lat: 28.212,
    lon: -177.36,
    timezone: "Pacific/Midway",
    breakType: "reef_pass",
    orientationDeg: 32,
    reefSlope: 0.09,
    depthAtBreakM: 1.5,
    tideStationId: "1612340",
    tideStationName: "Midway Atoll",
    tideStationDistanceKm: 0,
    blurb: "Genuinely remote, and the only spot in this list where the tide station is the break.",
  },
  {
    id: "kwajalein-pass",
    name: "Kwajalein Pass",
    region: "Kwajalein Atoll",
    country: "Marshall Islands",
    lat: 8.732,
    lon: 167.736,
    timezone: "Pacific/Kwajalein",
    breakType: "reef_pass",
    orientationDeg: 72,
    reefSlope: 0.1,
    depthAtBreakM: 1.3,
    tideStationId: "1820000",
    tideStationName: "Kwajalein Atoll",
    tideStationDistanceKm: 0,
    blurb: "A pass on the south-east rim of the atoll. Clean lines on a northerly, wall-to-wall on a big southerly.",
  },
  {
    id: "hanalei-bay",
    name: "Hanalei Bay",
    region: "Kauaʻi",
    country: "United States",
    lat: 22.205,
    lon: -159.5,
    timezone: "Pacific/Honolulu",
    breakType: "reef_pass",
    orientationDeg: 104,
    reefSlope: 0.12,
    depthAtBreakM: 1.2,
    tideStationId: null,
    tideStationName: null,
    tideStationDistanceKm: null,
    blurb:
      "No NOAA tide station in range, so Swellread refuses to score the tide factor here. Read the window, know that something is missing, do not invent it.",
  },
  {
    id: "ocean-beach-sf",
    name: "Ocean Beach",
    region: "San Francisco",
    country: "United States",
    lat: 37.759,
    lon: -122.511,
    timezone: "America/Los_Angeles",
    breakType: "beachbreak",
    orientationDeg: 292,
    reefSlope: 0.04,
    depthAtBreakM: 1.6,
    tideStationId: "9414290",
    tideStationName: "San Francisco",
    tideStationDistanceKm: 2,
    blurb: "Cold, steep, and completely exposed. The wind factor dominates everything else on a typical afternoon.",
  },
  {
    id: "fort-point",
    name: "Fort Point",
    region: "San Francisco",
    country: "United States",
    lat: 37.81,
    lon: -122.477,
    timezone: "America/Los_Angeles",
    breakType: "reef",
    orientationDeg: 302,
    reefSlope: 0.14,
    depthAtBreakM: 2.2,
    tideStationId: "9414290",
    tideStationName: "San Francisco",
    tideStationDistanceKm: 1,
    blurb: "A cobble ledge that only works in a real swell, and only with enough tide to keep it from grinding.",
  },
  {
    id: "arugam-bay",
    name: "Arugam Bay",
    region: "Arugam Bay",
    country: "Sri Lanka",
    lat: 6.833,
    lon: 81.82,
    timezone: "Asia/Colombo",
    breakType: "beachbreak",
    orientationDeg: 92,
    reefSlope: 0.04,
    depthAtBreakM: 1.3,
    tideStationId: null,
    tideStationName: null,
    tideStationDistanceKm: null,
    blurb:
      "Pointing right at the open Indian Ocean. South-west monsoon is the season. No tide station in range, so the app says so instead of guessing at the reef.",
  },
  {
    id: "kovalam",
    name: "Kovalam",
    region: "Kerala",
    country: "India",
    lat: 8.4,
    lon: 76.93,
    timezone: "Asia/Kolkata",
    breakType: "beachbreak",
    orientationDeg: 248,
    reefSlope: 0.04,
    depthAtBreakM: 1.4,
    tideStationId: null,
    tideStationName: null,
    tideStationDistanceKm: null,
    blurb: "South-west facing Arabian Sea beach. Monsoon swell, and the same missing-tide caveat as everywhere else on this coast.",
  },
  {
    id: "nazare",
    name: "Nazaré",
    region: "Leiria",
    country: "Portugal",
    lat: 39.6,
    lon: -9.085,
    timezone: "Europe/Lisbon",
    breakType: "beachbreak",
    orientationDeg: 290,
    reefSlope: 0.03,
    depthAtBreakM: 3.2,
    tideStationId: null,
    tideStationName: null,
    tideStationDistanceKm: null,
    blurb: "A canyon that focuses a north-west swell onto one very deep spot. Very little tide sensitivity, which the engine shows by scoring almost everything else.",
  },
  {
    id: "uluwatu",
    name: "Uluwatu",
    region: "Bali",
    country: "Indonesia",
    lat: -8.82,
    lon: 115.087,
    timezone: "Asia/Makassar",
    breakType: "reef",
    orientationDeg: 222,
    reefSlope: 0.12,
    depthAtBreakM: 1.0,
    tideStationId: null,
    tideStationName: null,
    tideStationDistanceKm: null,
    blurb: "A long shallow left with almost no take-off options. Low tide is a genuine hazard, so the reef-exposed gate matters more than the score.",
  },
];

const BY_ID = new Map(BREAKS.map((b) => [b.id, b]));

export function getBreak(id: string): SurfBreak | null {
  return BY_ID.get(id) ?? null;
}

export const HERO_BREAK_ID = "pago-pago";

export function getHeroBreak(): SurfBreak {
  const hero = BY_ID.get(HERO_BREAK_ID);
  if (!hero) throw new Error("hero break missing from catalogue");
  return hero;
}

export function listBreaks(): SurfBreak[] {
  return [...BREAKS];
}